"""empty message

Revision ID: 01cc5bf33c95
Revises: 0b3469dcb795
Create Date: 2018-05-09 13:53:39.193884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01cc5bf33c95'
down_revision = '0b3469dcb795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant', sa.Column('code', sa.String(length=8), nullable=False))
    op.create_unique_constraint(None, 'merchant', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchant', type_='unique')
    op.drop_column('merchant', 'code')
    # ### end Alembic commands ###
