"""empty message

Revision ID: 0b3469dcb795
Revises: 22fc7bed6e6f
Create Date: 2018-05-03 15:03:57.567282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3469dcb795'
down_revision = '22fc7bed6e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'portal_user', ['email'])
    op.create_unique_constraint(None, 'portal_user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portal_user', type_='unique')
    op.drop_constraint(None, 'portal_user', type_='unique')
    # ### end Alembic commands ###
