"""empty message

Revision ID: c2b3a300807b
Revises: 886ad723c31e
Create Date: 2018-04-30 12:12:22.000694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2b3a300807b'
down_revision = '886ad723c31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('float')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('float',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('merchant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], [u'merchant.id'], name=u'float_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
